<a href="https://colab.research.google.com/github/rishav2404/Data-Analysis/blob/main/Feature_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Feature Encoding**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df.head(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [ ]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
## Handling missing values
df.Gender.mode()

0    Male
Name: Gender, dtype: object

In [ ]:
df.Gender = df.Gender.fillna('Male')

In [ ]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

# **Label Encoding**

In [ ]:
le = preprocessing.LabelEncoder()
df['Gender_label'] = le.fit_transform(df.Gender.values)

In [ ]:
df.head(7)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0,1

In [ ]:
df.Gender_label.value_counts()

Gender_label
1    5457
0    4543
Name: count, dtype: int64

# **One Hot Encoding**

In [ ]:
# ohe = preprocessing.OneHotEncoder() # or can use pands.get_dummies

pd.get_dummies(df.Geography)

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [ ]:
df_dummies = pd.get_dummies(df)

df_dummies.head(7)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,True,False,False,True,False
1,608,41,1,83807.86,1,0,1,112542.58,0,0,False,False,True,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,0,True,False,False,True,False
3,699,39,1,0.00,2,0,0,93826.63,0,0,True,False,False,True,False
4,850,43,2,125510.82,1,1,1,79084.10,0,0,False,False,True,True,False
5,645,44,8,113755.78,2,1,0,149756.71,1,1,False,False,True,False,True
6,822,50,7,0.00,2,1,1,10062.80,0,1,True,False,False,False,True

#### Dummy Encoding

In [ ]:
df_dummies_de = pd.get_dummies(df,drop_first=True) # one of the feature is gone

df_dummies_de.head(7)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,0,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,0,False,True,False
5,645,44,8,113755.78,2,1,0,149756.71,1,1,False,True,True
6,822,50,7,0.00,2,1,1,10062.80,0,1,False,False,True

# **Target Encoding**

In [ ]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.8.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.14.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.8.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 3.9 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.8.1

In [ ]:
from category_encoders import TargetEncoder

In [ ]:
encoder  = TargetEncoder()

df1 = pd.read_csv('/content/Churn_Modelling.csv')

# df1.head(7)

In [ ]:
df1.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [ ]:
df1.Gender = df1.Gender.fillna('Male')

In [ ]:
df1.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
encoder = TargetEncoder()

df1['Gender_Encoded'] = encoder.fit_transform(df1.Gender,df1.Exited)

In [ ]:
df1.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Encoded
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.250715
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.250715
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0.250715
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.250715
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0.250715

In [ ]:
df1.Gender_Encoded.value_counts()

Gender_Encoded
0.164559    5457
0.250715    4543
Name: count, dtype: int64

####Benifits of Tagret Encoding
- It is simple and quick encoding meathod that doesn't add to the dimensionality of the dataset.

####Limitations of TE
- It is dependent on the target distribution which means target encoding requires careful validation as it can be prone to overfitting.

# **Hash Encoder**

In [ ]:
from category_encoders import HashingEncoder

# ce = HashingEncoder(n_components=3)
# ce_hashing = ce.fit_transform(df.Geography)
# ce_hashing.head(7)

In [ ]:
X = df.Gender
y = df.Exited

In [ ]:
ce_hash = HashingEncoder(cols=['Gender'])
ce_hash.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      0      0      0      0      0      0      1
1         0      0      0      0      0      0      0      1
2         0      0      0      0      0      0      0      1
3         0      0      0      0      0      0      0      1
4         0      0      0      0      0      0      0      1
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      0      0      0      0      1      0      0
9996      0      0      0      0      0      1      0      0
9997      0      0      0      0      0      0      0      1
9998      0      0      0      0      0      1      0      0
9999      0      0      0      0      0      0      0      1

[10000 rows x 8 columns]

In [ ]:
X = df.Geography
y = df.Exited

ce_hash = HashingEncoder(cols=['Geography'])
ce_hash.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      1      0      0      0      0      0      0
1         0      0      0      1      0      0      0      0
2         0      1      0      0      0      0      0      0
3         0      1      0      0      0      0      0      0
4         0      0      0      1      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      1      0      0      0      0      0      0
9996      0      1      0      0      0      0      0      0
9997      0      1      0      0      0      0      0      0
9998      0      0      0      0      0      0      0      1
9999      0      1      0      0      0      0      0      0

[10000 rows x 8 columns]

In [ ]:
ce_hash = HashingEncoder(n_components=16, cols=['Geography']) # 16 columns will be created
ce_hash.fit_transform(X,y)

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9996,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9997,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9999,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0